### ISSUE TITLE
Incorrect function description

### ISSUE THREAD

**Issue by fatihgvn** [OpenNuvoton/Nano103BSP#1]
https://github.com/OpenNuvoton/Nano103BSP/blob/8193210678cfcc81415fbeb6fbe51815ce3c811d/Library/StdDriver/src/clk.c#L591C83-L591C83

`28MHz => 699050us`  to `**24MHz** => 699050us`

**Comment by ychuang3** [comment]
Yes, it should be 24MHz.
typo fixed
Thank you.
